init:
    $ generate_dark_version = True

    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '06')
    $ generate_img('Olya', 'Prof', 'm_day', '00', 'good', 'aside', '07')
    $ generate_img('Olya', 'Prof', 'b_day', '00', 'good', 'aside', '01')

    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '00')
    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Prof', 'b_evening', '00', 'good', 'aside', '06')

    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '00')
    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Prof', 'm_evening', '00', 'good', 'aside', '06')

    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '00')
    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '01')
    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '02')
    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '03')
    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '04')
    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '05')
    $ generate_img('Olya', 'Prof', 'm_evening', '01', 'good', 'aside', '06')


    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'm_day', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'b_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_day', '00', 'good', 'ahead', '04')

    $ generate_img('Olya', 'Amaze', 'm_evening', '00', 'good', 'ahead', '01', blur = 'blur')
    $ generate_img('Olya', 'Amaze', 'm_evening', '00', 'good', 'ahead', '02', blur = 'blur')
    $ generate_img('Olya', 'Amaze', 'm_evening', '00', 'good', 'ahead', '03', blur = 'blur')
    $ generate_img('Olya', 'Amaze', 'm_evening', '00', 'good', 'ahead', '04', blur = 'blur')
    $ generate_img('Olya', 'Amaze', 'm_evening', '00', 'good', 'ahead', '05', blur = 'blur')

    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'b_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'b_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '07')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '00', 'good', 'aside', '08')

    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '07')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '01', 'good', 'aside', '08')

    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '01')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '02')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '03')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '04')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '05')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '06')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '07')
    $ generate_img('Olya', 'Amaze', 'b_evening_winter', '02', 'good', 'aside', '08')

    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'm_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'm_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Amaze', 'm_evening_winter', '01', 'good', 'ahead', '07')




    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '04')

    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'm_day', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'm_evening', '00', 'good', 'ahead', '01', blur = 'blur')

    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_evening', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_evening_winter', '01', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_day', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_day', '01', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '06')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '07')
    $ generate_img('Olya', 'Happy', 'b_dark', '00', 'good', 'aside', '08')

    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'b_dark', '01', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'm_day', '01', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'm_dark', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'm_dark', '01', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '00', 'good', 'ahead', '08')

    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Happy', 'm_evening_winter', '01', 'good', 'ahead', '08')



    $ generate_img('Olya', 'Serious', 'b_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_day', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Serious', 'b_night', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_night', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_night', '01', 'good', 'ahead')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '03')

    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '01', blur = 'blur')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '05', blur = 'blur')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', blur = 'blur')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', blur = 'blur')

    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening', '02', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening', '03', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening', '04', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'b_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'b_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '08')
    $ generate_img('Olya', 'Serious', 'b_evening', '00', 'good', 'ahead', '09')

    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '08')
    $ generate_img('Olya', 'Serious', 'b_evening', '01', 'good', 'ahead', '09')

    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '08')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '00', 'good', 'ahead', '09')

    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '08')
    $ generate_img('Olya', 'Serious', 'b_evening_winter', '01', 'good', 'ahead', '09')

    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Serious', 'm_evening_winter', '02', 'good', 'ahead', '07')


    $ generate_img('Olya', 'Suffer', 'b_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_day', '00', 'good', 'ahead', '07')
    $ generate_img('Olya', 'Suffer', 'm_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_night', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_night', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'b_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'b_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'm_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'm_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_dark2', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '00', 'good', 'ahead', '05')

    $ generate_img('Olya', 'Suffer', 'b_dark2', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_dark2', '01', 'good', 'ahead', '05')

    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'm_evening', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'm_evening', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'b_evening', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Suffer', 'm_evening_winter', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '00', 'good', 'ahead', '05')

    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Suffer', 'b_evening_winter2', '01', 'good', 'ahead', '05')


    $ generate_img('Olya', 'Weeps', 'b_day', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_day', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_day', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_day', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_day', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'm_day', '00', 'good', 'ahead')
    $ generate_img('Olya', 'Weeps', 'b_night', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_night', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_night', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_night', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_night', '00', 'good', 'ahead', '05')

    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_dark', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_dark', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'ahead', '04')

    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'm_dark', '00', 'good', 'aside', '04')

    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'ahead', '04')

    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'm_dark', '01', 'good', 'aside', '04')

    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'ahead', '04')

    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'm_dark', '02', 'good', 'aside', '04')

    $ generate_img('Olya', 'Weeps', 'm_night', '00', 'good', 'ahead')
    $ generate_img('Olya', 'Weeps', 'm_night', '01', 'good', 'ahead')

    $ generate_img('Olya', 'Weeps', 'm_evening', '00', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Weeps', 'm_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_evening', '00', 'good', 'ahead', '03')

    $ generate_img('Olya', 'Weeps', 'm_evening', '01', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Weeps', 'm_evening', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_evening', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_evening', '01', 'good', 'ahead', '03')

    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '00', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '00', 'good', 'ahead', '03')

    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '01', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'm_evening_winter', '01', 'good', 'ahead', '03')

    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '00')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '00')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', 'good', 'aside', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening', '01', 'good', 'aside', '07')



    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'ahead', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '00', 'good', 'aside', '07')

    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '01')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '02')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '03')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '04')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '05')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '06')
    $ generate_img('Olya', 'Weeps', 'b_evening_winter', '01', 'good', 'aside', '07')

    $ generate_img('Olya', 'Mask', 'b_night', '00')
    $ generate_img('Olya', 'Mask', 'm_night', '00')


    $ generate_img('Olya', 'Happy', 'b_evening', '00', "good", "ahead", "07")
    $ generate_img('Olya', 'Serious', 'b_evening', '00', "good", "ahead", "01")
    $ generate_img('Olya', 'Weeps', 'b_evening', '00', "good", "ahead", "02")
    $ generate_img('Olya', 'Suffer', 'b_evening', '00', "good", "ahead", "04")

    $ generate_dark_version = False


    $ generate_img('Olya', 'Color', 'default', '00', "good", "ahead", "01")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "ahead", "02")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "ahead", "03")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "ahead", "04")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "ahead", "05")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "ahead", "06")

    $ generate_img('Olya', 'Color', 'default', '00', "good", "aside", "01")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "aside", "02")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "aside", "03")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "aside", "04")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "aside", "05")
    $ generate_img('Olya', 'Color', 'default', '00', "good", "aside", "06")


    $ generate_img('Olya', 'Zulka', 'b_day', '00', "good", "ahead", "01")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "good", "ahead", "02")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "good", "ahead", "03")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "good", "ahead", "04")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "anger", "ahead", "01")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "anger", "ahead", "02")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "anger", "ahead", "03")
    $ generate_img('Olya', 'Zulka', 'b_day', '00', "anger", "ahead", "04")

    $ generate_img('Olya', 'Zulka', 'm_day', '00', "good", "ahead", "01")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "good", "ahead", "02")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "good", "ahead", "03")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "good", "ahead", "04")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "anger", "ahead", "01")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "anger", "ahead", "02")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "anger", "ahead", "03")
    $ generate_img('Olya', 'Zulka', 'm_day', '00', "anger", "ahead", "04")
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
